name: CI Build
on:
 push:
   branches:
     - "**" #Trigger this github action on every branch
jobs:
 build:
   name: Maven Build
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Setup Java 17
       uses: actions/setup-java@v3
       with:
         java-version: 17
         distribution: "temurin"
         cache: "maven"
     - name: Build and test with Maven
       run: mvn clean verify #compile, execute tests and verify project