---
name: CI Build
'on':
  push:
    branches:
      - '**'
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          cache: maven
          distribution: temurin
          java-version: 17
      - name: Create application-test.properties
        run: |
          echo "Start create configuration file"
          echo "spring.datasource.driver-class-name=${{vars.APP_CONFIG_SPRING_DATASOURCE_DRIVER_CLASS_NAME}}" >> src/test/resources/application-test.properties
          echo "spring.jpa.hibernate.ddl-auto=${{vars.APP_CONFIG_SPRING_JPA_HIBERNATE_DDL_AUTO}}" >> src/test/resources/application-test.properties
          echo "jwt.secret=${{secrets.APP_CONFIG_JWT_SECRET}}" >> src/test/resources/application-test.properties
          echo "spring.mail.host=${{secrets.APP_CONFIG_SPRING_MAIL_HOST}}" >> src/test/resources/application-test.properties
          echo "spring.mail.port=${{secrets.APP_CONFIG_SPRING_MAIL_PORT}}" >> src/test/resources/application-test.properties
          echo "spring.mail.username=${{secrets.APP_CONFIG_SPRING_MAIL_USERNAME}}" >> src/test/resources/application-test.properties
          echo "spring.mail.password=${{secrets.APP_CONFIG_SPRING_MAIL_PASSWORD}}" >> src/test/resources/application-test.properties
          echo "spring.mail.properties.mail.smtp.auth=${{secrets.APP_CONFIG_SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}}" >> src/test/resources/application-test.properties
          echo "spring.mail.properties.mail.smtp.starttls.enable=${{secrets.APP_CONFIG_SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}}" >> src/test/resources/application-test.properties
          echo "File created"
      - name: Build and test with Maven
        run: mvn clean verify